# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool: mynewcomp



steps:
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '18'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'LocalDirectory'
    jdkFile: 'C:\jdk1.8.0_172\jdk1.8.0_172 (1).7z'
    cleanDestinationDirectory: false
- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'install'
    mavenOptions: '-Xmx3072m'
    mavenVersionOption: 'Default'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '18'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
